import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "../components/DashboardHeader";
import LandingHeader from "@/components/LandingHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html>
        <body className="dark:text-white dark:bg-zinc-950">{children}</body>
      </html>
    </ClerkProvider>
  );
}
